---
name: Test

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: npm

      - name: Install dependencies
        run: make install

      - name: Linting
        run: make eslint

      - name: Test
        run: make test

      - name: Validate package
        run: make validate-package
